qcacld-3.0: Cleanup unused variables introduced via LA.UM.9.12.r1-08400
Subsequent to 0e74ab4 ("qcacld-3.0: Merge tag
'LA.UM.9.12.r1-08400-SMxx50.0' into neutrino-msm-hotdogb-4.14")

These are likely related to disabled debugging functions or are
otherwise guarded by configs which we do not use. Mark as
__maybe_unused to keep the code intact and retain theoretical
functionality rather than nuking these variables outright.

This fixes the following compilation errors:

../drivers/staging/qcacld-3.0/core/mac/src/pe/lim/lim_send_management_frames.c:5385:19: error: unused variable 'fc' [-Werror,-Wunused-variable]
        tpSirMacFrameCtl fc = (tpSirMacFrameCtl)frame;
                         ^

../drivers/staging/qcacld-3.0/core/mac/src/pe/lim/lim_utils.c:1286:22: error: unused variable 'lim_params' [-Werror,-Wunused-variable]
                tLimNoShortParams *lim_params =
                                   ^

[@0ctobot: Restore 'third_index' variable to it's new location,
reverting commit 3d3d5ae ("qcacmn: Remove unused 'third_index' variable")]
Signed-off-by: Adam W. Willis <return.of.octobot@gmail.com>